/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates */
        get: operations["templates_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Packs */
        get: operations["packs_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Variants */
        get: operations["variants_variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Variants Propose */
        post: operations["variants_propose_variants_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Packs Propose
         * @description Propose multi-page packs from the existing page catalog; optionally pair with variants.
         */
        post: operations["packs_propose_packs_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brands */
        get: operations["list_brands_brands_get"];
        put?: never;
        /** Create Brand */
        post: operations["create_brand_brands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand */
        get: operations["get_brand_brands__brand_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Brand */
        patch: operations["patch_brand_brands__brand_id__patch"];
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_posts__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/pages/{page_id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Preview Html
         * @description Browser-ready filled HTML for iframe / srcdoc (images inlined as data URIs).
         */
        get: operations["get_page_preview_html_posts__post_id__pages__page_id__html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Images */
        post: operations["post_images_posts__post_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/compose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Compose */
        post: operations["post_compose_posts__post_id__compose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Render
         * @description Generate download PNGs from filled HTML (Playwright + storage upload).
         */
        post: operations["post_render_posts__post_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/animate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Animate */
        post: operations["post_animate_posts__post_id__animate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Resize */
        post: operations["post_resize_posts__post_id__resize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/redesign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Redesign */
        post: operations["post_redesign_posts__post_id__redesign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Rewrite */
        post: operations["post_rewrite_posts__post_id__rewrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_posts__post_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Revisions */
        get: operations["get_revisions_posts__post_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Undo */
        post: operations["post_undo_posts__post_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnimateRequest */
        AnimateRequest: {
            /** Page Id */
            page_id?: string | null;
            /** Pages */
            pages?: string[] | null;
            /**
             * Motion Preset
             * @default fade_kenburns
             */
            motion_preset: string;
        };
        /** BrandOut */
        BrandOut: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Website */
            website?: string | null;
            /** Logo */
            logo?: string | null;
            /** Formats */
            formats?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[];
        };
        /** ComposeRequest */
        ComposeRequest: {
            /** Pages */
            pages?: string[] | null;
            /**
             * Ensure Images
             * @default true
             */
            ensure_images: boolean;
        };
        /** CreateBrandBody */
        CreateBrandBody: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Website */
            website?: string | null;
            /** Logo */
            logo?: string | null;
            /** Formats */
            formats?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[];
        };
        /** CreatePostRequest */
        CreatePostRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Brand Id */
            brand_id?: string | null;
            /** Pack Id */
            pack_id?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Format */
            format?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post") | null;
            /** Variant Id */
            variant_id?: string | null;
            /**
             * With Images
             * @default false
             */
            with_images: boolean;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Decision */
            decision: string;
            /** Reasons */
            reasons?: string[];
            /**
             * Note
             * @default
             */
            note: string;
            /** Page Id */
            page_id?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Id */
            id: string;
            /** Post Id */
            post_id: string;
            /** Decision */
            decision: string;
            /** Reasons */
            reasons: unknown[];
            /** Note */
            note: string;
            /** Page Id */
            page_id: string | null;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ImagesRequest */
        ImagesRequest: {
            /** Pages */
            pages?: string[] | null;
            /**
             * Regenerate
             * @default false
             */
            regenerate: boolean;
        };
        /** ListBrandsOut */
        ListBrandsOut: {
            /** Brands */
            brands: components["schemas"]["BrandOut"][];
        };
        /** ListIdsResponse */
        ListIdsResponse: {
            /** Ids */
            ids: string[];
        };
        /** ListPacksResponse */
        ListPacksResponse: {
            /** Packs */
            packs: components["schemas"]["PackSummary"][];
        };
        /** ListPostsResponse */
        ListPostsResponse: {
            /** Posts */
            posts: components["schemas"]["PostResponse"][];
        };
        /** ListRevisionsResponse */
        ListRevisionsResponse: {
            /** Revisions */
            revisions: components["schemas"]["RevisionItem"][];
        };
        /** ListVariantsResponse */
        ListVariantsResponse: {
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /** PackSummary */
        PackSummary: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Pages */
            pages: number;
            /** Images */
            images: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** PatchBrandBody */
        PatchBrandBody: {
            /** Name */
            name?: string | null;
            /** Tagline */
            tagline?: string | null;
            /** Description */
            description?: string | null;
            /** Website */
            website?: string | null;
            /** Logo */
            logo?: string | null;
            /** Formats */
            formats?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[] | null;
        };
        /** PostResponse */
        PostResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Brand Id */
            brand_id: string | null;
            /** Status */
            status: string;
            /** Url */
            url: string;
            /** Format */
            format: string;
            /** Pack Id */
            pack_id: string | null;
            /** Template Id */
            template_id: string | null;
            /** Variant Id */
            variant_id: string | null;
            /** Asset Dir */
            asset_dir: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Images */
            images: {
                [key: string]: unknown;
            };
            /** Composed */
            composed: {
                [key: string]: unknown;
            };
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ProposePacksRequest */
        ProposePacksRequest: {
            /** Brand Id */
            brand_id?: string | null;
            /**
             * Format
             * @default ig_portrait
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /**
             * Count
             * @default 2
             */
            count: number;
            /**
             * With Variants
             * @default true
             */
            with_variants: boolean;
            /**
             * Variant Count
             * @default 3
             */
            variant_count: number;
            /**
             * Brief
             * @default
             */
            brief: string;
        };
        /** ProposePacksResponse */
        ProposePacksResponse: {
            /** Packs */
            packs: {
                [key: string]: unknown;
            }[];
            /** Saved Pack Ids */
            saved_pack_ids: string[];
            /** Variants */
            variants?: {
                [key: string]: unknown;
            }[];
            /** Saved Variant Ids */
            saved_variant_ids?: string[];
        };
        /** ProposeVariantsRequest */
        ProposeVariantsRequest: {
            /** Brand Id */
            brand_id: string;
            /** Template Id */
            template_id?: string | null;
            /** Pack Id */
            pack_id?: string | null;
            /**
             * Count
             * @default 3
             */
            count: number;
        };
        /** ProposeVariantsResponse */
        ProposeVariantsResponse: {
            /** Variants */
            variants: {
                [key: string]: unknown;
            }[];
            /** Saved Ids */
            saved_ids: string[];
        };
        /** RedesignRequest */
        RedesignRequest: {
            /** Variant Id */
            variant_id?: string | null;
            /**
             * Propose
             * @default false
             */
            propose: boolean;
            /**
             * Regenerate Images
             * @default false
             */
            regenerate_images: boolean;
            /**
             * Recompose
             * @default true
             */
            recompose: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** ResizeRequest */
        ResizeRequest: {
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Pages */
            pages?: string[] | null;
            /**
             * Apply To Post
             * @default true
             */
            apply_to_post: boolean;
        };
        /** RevisionItem */
        RevisionItem: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
        };
        /** RewriteRequest */
        RewriteRequest: {
            /** Text */
            text?: {
                [key: string]: unknown;
            } | null;
            /** Caption */
            caption?: string | null;
            /**
             * Suggest
             * @default false
             */
            suggest: boolean;
            /**
             * Recompose
             * @default false
             */
            recompose: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantOut */
        VariantOut: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Css Vars */
            css_vars: {
                [key: string]: unknown;
            };
            /** Brand Id */
            brand_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    templates_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListIdsResponse"];
                };
            };
        };
    };
    packs_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPacksResponse"];
                };
            };
        };
    };
    variants_variants_get: {
        parameters: {
            query: {
                /** @description Brand UUID or slug */
                brand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListVariantsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    variants_propose_variants_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeVariantsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposeVariantsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    packs_propose_packs_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposePacksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposePacksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_brands_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBrandsOut"];
                };
            };
        };
    };
    create_brand_brands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrandBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_brands__brand_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_brand_brands__brand_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBrandBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_posts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPostsResponse"];
                };
            };
        };
    };
    create_post_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_preview_html_posts__post_id__pages__page_id__html_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_images_posts__post_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_compose_posts__post_id__compose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ComposeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_render_posts__post_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ComposeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_animate_posts__post_id__animate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnimateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_resize_posts__post_id__resize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_redesign_posts__post_id__redesign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedesignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_rewrite_posts__post_id__rewrite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_feedback_posts__post_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revisions_posts__post_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRevisionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_undo_posts__post_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
