/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Packs */
        get: operations["packs_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack Detail */
        get: operations["get_pack_detail_packs__pack_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packs/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Packs Propose
         * @description Propose multi-page packs from the existing page catalog.
         */
        post: operations["packs_propose_packs_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brands */
        get: operations["list_brands_brands_get"];
        put?: never;
        /** Create Brand */
        post: operations["create_brand_brands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/enrich-from-website": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrich From Website
         * @description Scrape a website and draft an About blurb. Does not save the brand.
         */
        post: operations["enrich_from_website_brands_enrich_from_website_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand */
        get: operations["get_brand_brands__brand_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Brand */
        patch: operations["patch_brand_brands__brand_id__patch"];
        trace?: never;
    };
    "/brands/{brand_id}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Brand Logo */
        post: operations["upload_brand_logo_brands__brand_id__logo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Posts
         * @description List posts. Pass ?include=html to embed each page's preview markup.
         *
         *     Full HTML is omitted by default: a queue load can be dozens of posts,
         *     each with several pages, and most callers only need metadata.
         */
        get: operations["list_posts_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_posts__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Images */
        post: operations["post_images_posts__post_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/compose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Compose */
        post: operations["post_compose_posts__post_id__compose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Render
         * @description Generate download PNGs from filled HTML (Playwright + storage upload).
         */
        post: operations["post_render_posts__post_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/animate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Animate */
        post: operations["post_animate_posts__post_id__animate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Resize */
        post: operations["post_resize_posts__post_id__resize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/redesign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Redesign */
        post: operations["post_redesign_posts__post_id__redesign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Rewrite */
        post: operations["post_rewrite_posts__post_id__rewrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_posts__post_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Revisions */
        get: operations["get_revisions_posts__post_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Undo */
        post: operations["post_undo_posts__post_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Source Endpoint */
        post: operations["ingest_source_endpoint_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Run */
        patch: operations["patch_run_runs__run_id__patch"];
        trace?: never;
    };
    "/runs/{run_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Run Source */
        post: operations["add_run_source_runs__run_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Run */
        post: operations["suggest_run_runs__run_id__suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Run */
        post: operations["generate_run_runs__run_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Template
         * @description Upload a PNG/JPEG/WebP mockup → vision LLM HTML draft (not persisted).
         */
        post: operations["extract_template_templates_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_templates__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnimateRequest */
        AnimateRequest: {
            /** Page Id */
            page_id?: string | null;
            /** Pages */
            pages?: string[] | null;
            /**
             * Motion Preset
             * @default fade_kenburns
             */
            motion_preset: string;
        };
        /** Body_extract_template_templates_extract_post */
        Body_extract_template_templates_extract_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Format
             * @default
             */
            format: string;
        };
        /** Body_upload_brand_logo_brands__brand_id__logo_post */
        Body_upload_brand_logo_brands__brand_id__logo_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BrandOut */
        BrandOut: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Website */
            website?: string | null;
            /** Logo */
            logo?: string | null;
            /** Formats */
            formats?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[];
        };
        /** ComposeRequest */
        ComposeRequest: {
            /** Pages */
            pages?: string[] | null;
            /**
             * Ensure Images
             * @default true
             */
            ensure_images: boolean;
        };
        /** CreateBrandBody */
        CreateBrandBody: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Tagline
             * @default
             */
            tagline: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Website */
            website?: string | null;
            /** Logo */
            logo?: string | null;
            /** Formats */
            formats?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[];
        };
        /** CreateTemplateRequest */
        CreateTemplateRequest: {
            /** Slug */
            slug: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Format
             * @default ig_feed
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Html */
            html: string;
            /** Source Image Url */
            source_image_url?: string | null;
        };
        /** EnrichWebsiteBody */
        EnrichWebsiteBody: {
            /**
             * Website
             * Format: uri
             */
            website: string;
            /**
             * Brand Name
             * @default
             */
            brand_name: string;
        };
        /** EnrichWebsiteOut */
        EnrichWebsiteOut: {
            /** Description */
            description: string;
        };
        /** ExtractTemplateResponse */
        ExtractTemplateResponse: {
            /** Html */
            html: string;
            /** Suggested Slug */
            suggested_slug: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Source Image Url */
            source_image_url?: string | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Decision */
            decision: string;
            /** Reasons */
            reasons?: string[];
            /**
             * Note
             * @default
             */
            note: string;
            /** Page Id */
            page_id?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Id */
            id: string;
            /** Post Id */
            post_id: string;
            /** Decision */
            decision: string;
            /** Reasons */
            reasons: unknown[];
            /** Note */
            note: string;
            /** Page Id */
            page_id: string | null;
            /** Created At */
            created_at: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Source Ids */
            source_ids: string[];
            /**
             * Instruction
             * @default
             */
            instruction: string;
            /** Suggestion Ids */
            suggestion_ids?: string[];
            /** Brand Id */
            brand_id?: string | null;
            /** Pack Id */
            pack_id?: string | null;
            /** Template Id */
            template_id?: string | null;
            /** Design */
            design?: ("pack" | "template") | null;
            /** Format */
            format?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post") | null;
            /** Image Style */
            image_style?: ("realistic" | "illustration") | null;
            /**
             * With Images
             * @default false
             */
            with_images: boolean;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Posts */
            posts: components["schemas"]["PostResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ImagesRequest */
        ImagesRequest: {
            /** Pages */
            pages?: string[] | null;
            /**
             * Regenerate
             * @default false
             */
            regenerate: boolean;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Url */
            url?: string | null;
            /** Text */
            text?: string | null;
        };
        /** ListBrandsOut */
        ListBrandsOut: {
            /** Brands */
            brands: components["schemas"]["BrandOut"][];
        };
        /** ListPacksResponse */
        ListPacksResponse: {
            /** Packs */
            packs: components["schemas"]["PackSummary"][];
        };
        /** ListPostsResponse */
        ListPostsResponse: {
            /** Posts */
            posts: components["schemas"]["PostResponse"][];
        };
        /** ListRevisionsResponse */
        ListRevisionsResponse: {
            /** Revisions */
            revisions: components["schemas"]["RevisionItem"][];
        };
        /** ListRunsResponse */
        ListRunsResponse: {
            /** Runs */
            runs: components["schemas"]["RunResponse"][];
            /** Max Run Sources */
            max_run_sources: number;
            /** Default Suggested Posts */
            default_suggested_posts: number;
            /** Max Suggested Posts */
            max_suggested_posts: number;
        };
        /** ListTemplatesResponse */
        ListTemplatesResponse: {
            /** Templates */
            templates: components["schemas"]["TemplateSummary"][];
            /** Ids */
            ids?: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
        };
        /** PackDetail */
        PackDetail: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Formats */
            formats: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[];
            /** Pages */
            pages: number;
            /** Images */
            images: number;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Preview Html
             * @default
             */
            preview_html: string;
        };
        /** PackSummary */
        PackSummary: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Formats */
            formats: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[];
            /** Pages */
            pages: number;
            /** Images */
            images: number;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Preview Html
             * @default
             */
            preview_html: string;
        };
        /** PatchBrandBody */
        PatchBrandBody: {
            /** Name */
            name?: string | null;
            /** Tagline */
            tagline?: string | null;
            /** Description */
            description?: string | null;
            /** Website */
            website?: string | null;
            /** Logo */
            logo?: string | null;
            /** Formats */
            formats?: ("ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post")[] | null;
        };
        /** PatchRunRequest */
        PatchRunRequest: {
            /** Sources */
            sources?: components["schemas"]["SourceRef"][] | null;
            /** Instruction */
            instruction?: string | null;
        };
        /** PostResponse */
        PostResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Brand Id */
            brand_id: string | null;
            /** Status */
            status: string;
            /** Format */
            format: string;
            /** Pack Id */
            pack_id: string | null;
            /** Template Id */
            template_id: string | null;
            /** Image Style */
            image_style: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Images */
            images: {
                [key: string]: unknown;
            };
            /** Composed */
            composed: {
                [key: string]: unknown;
            };
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ProposePacksRequest */
        ProposePacksRequest: {
            /** Brand Id */
            brand_id?: string | null;
            /**
             * Format
             * @default ig_portrait
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /**
             * Count
             * @default 2
             */
            count: number;
            /**
             * Brief
             * @default
             */
            brief: string;
        };
        /** ProposePacksResponse */
        ProposePacksResponse: {
            /** Packs */
            packs: {
                [key: string]: unknown;
            }[];
            /** Saved Pack Ids */
            saved_pack_ids: string[];
        };
        /** RedesignRequest */
        RedesignRequest: {
            /** Image Style */
            image_style?: ("realistic" | "illustration") | null;
            /**
             * Regenerate Images
             * @default false
             */
            regenerate_images: boolean;
            /**
             * Recompose
             * @default true
             */
            recompose: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** ResizeRequest */
        ResizeRequest: {
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Pages */
            pages?: string[] | null;
            /**
             * Apply To Post
             * @default true
             */
            apply_to_post: boolean;
        };
        /** RevisionItem */
        RevisionItem: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Version */
            version: number;
            /** Created At */
            created_at: string;
        };
        /** RewriteRequest */
        RewriteRequest: {
            /** Text */
            text?: {
                [key: string]: unknown;
            } | null;
            /** Caption */
            caption?: string | null;
            /**
             * Suggest
             * @default false
             */
            suggest: boolean;
            /**
             * Recompose
             * @default false
             */
            recompose: boolean;
        };
        /** RunResponse */
        RunResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** Cards */
            cards: components["schemas"]["SourceCard"][];
            /** Instruction */
            instruction: string;
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionBrief"][];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** SourceCard */
        SourceCard: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Canonical Url
             * @default
             */
            canonical_url: string;
            /**
             * Thumbnail Url
             * @default
             */
            thumbnail_url: string;
            /**
             * Duration
             * @default
             */
            duration: string;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /**
             * Page Type
             * @default
             */
            page_type: string;
        };
        /** SourceRef */
        SourceRef: {
            /** Id */
            id: string;
            /**
             * Kind
             * @default html
             */
            kind: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /** SuggestRequest */
        SuggestRequest: {
            /** Source Ids */
            source_ids: string[];
            /**
             * Instruction
             * @default
             */
            instruction: string;
            /** Count */
            count?: number | null;
        };
        /** SuggestResponse */
        SuggestResponse: {
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionBrief"][];
        };
        /** SuggestionBrief */
        SuggestionBrief: {
            /** Id */
            id: string;
            /** Headline */
            headline: string;
            /** Text */
            text: string;
            /** Reason */
            reason: string;
        };
        /** TemplateDetail */
        TemplateDetail: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /** Html */
            html: string;
            /**
             * Preview Html
             * @default
             */
            preview_html: string;
            /** Source Image Url */
            source_image_url?: string | null;
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
        };
        /** TemplateSummary */
        TemplateSummary: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ig_feed" | "ig_portrait" | "ig_story" | "tiktok" | "fb_post" | "x_post";
            /**
             * Preview Html
             * @default
             */
            preview_html: string;
            /**
             * Is System
             * @default false
             */
            is_system: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    packs_packs_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPacksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pack_detail_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    packs_propose_packs_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposePacksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposePacksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_brands_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBrandsOut"];
                };
            };
        };
    };
    create_brand_brands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrandBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_from_website_brands_enrich_from_website_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichWebsiteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichWebsiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_brands__brand_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_brand_brands__brand_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBrandBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_brand_logo_brands__brand_id__logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_brand_logo_brands__brand_id__logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_posts_get: {
        parameters: {
            query?: {
                include?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPostsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_images_posts__post_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_compose_posts__post_id__compose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ComposeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_render_posts__post_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ComposeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_animate_posts__post_id__animate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnimateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_resize_posts__post_id__resize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_redesign_posts__post_id__redesign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedesignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_rewrite_posts__post_id__rewrite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_feedback_posts__post_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revisions_posts__post_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRevisionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_undo_posts__post_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_source_endpoint_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsResponse"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_run_runs__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_run_source_runs__run_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_run_runs__run_id__suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_run_runs__run_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_templates_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTemplatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_template_templates_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_template_templates_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_templates__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
